export const AFF = {
  aviasales: 'https://www.aviasales.com/?marker=716647',
  airalo: 'https://airalo.tpo.lv/KDAmYfab',
  airhelp: 'https://airhelp.tpo.lv/irNfNVGG',
  booking: 'https://www.booking.com/?aid=7914697',
  premium: '/api/upgrade/premium',
  elite: '/api/upgrade/elite',
};

export const MOCK_DEALS = {
  errorFares: [
    {
      id: 'ef1',
      type: 'error_fare' as const,
      badge: '🚨 Error Fare',
      route: 'JFK → Milan, Italy',
      emoji: '🇮🇹',
      price: '$143',
      originalPrice: '$850',
      savings: '83% off',
      detail: 'TAP Air Portugal via Lisbon · RT\nMay 5–15 · May 12–22 · Found 23 min ago',
      bookUrl: 'https://www.aviasales.com/?marker=716647&origin=JFK&destination=MXP&depart_date=2026-05-05&return_date=2026-05-15',
      ctaText: 'Book Now',
      isLive: true,
      liveStatus: 'live' as const,
      foundMinutesAgo: 23,
    },
    {
      id: 'ef2',
      type: 'error_fare' as const,
      badge: '🚨 Error Fare',
      route: 'ORD → Cancún',
      emoji: '🇲🇽',
      price: '$89',
      originalPrice: '$890',
      savings: '90% off',
      detail: 'American Airlines · Nonstop · RT\nApr 28–May 8 · Found 1hr ago',
      bookUrl: 'https://www.aviasales.com/?marker=716647&origin=ORD&destination=CUN&depart_date=2026-04-28&return_date=2026-05-08',
      ctaText: 'Book Now',
      isLive: true,
      liveStatus: 'live' as const,
      foundMinutesAgo: 60,
    },
    {
      id: 'ef3',
      type: 'error_fare' as const,
      badge: '🚨 Error Fare',
      route: 'LAX → Tokyo',
      emoji: '🇯🇵',
      price: '$487',
      originalPrice: '$1,100',
      savings: '56% off',
      detail: 'ANA via Tokyo · RT\nOct 2026 · Found 2hrs ago',
      bookUrl: 'https://www.aviasales.com/?marker=716647&origin=LAX&destination=NRT&depart_date=2026-10-01&return_date=2026-10-14',
      ctaText: 'Book Now',
      isLive: true,
      liveStatus: 'unconfirmed' as const,
      foundMinutesAgo: 120,
    },
    {
      id: 'ef4',
      type: 'error_fare' as const,
      badge: '🚨 Error Fare',
      route: 'SFO → Paris',
      emoji: '🇫🇷',
      price: '$312',
      originalPrice: '$870',
      savings: '64% off',
      detail: 'Air France · RT\nJun 2026 · Found 45min ago',
      bookUrl: 'https://www.aviasales.com/?marker=716647&origin=SFO&destination=CDG&depart_date=2026-06-01&return_date=2026-06-15',
      ctaText: 'Book Now',
      isLive: true,
      liveStatus: 'live' as const,
      foundMinutesAgo: 45,
    },
  ],
  points: [
    {
      id: 'p1',
      type: 'points' as const,
      badge: '✈️ Points Deal',
      route: 'ANA Business · Tokyo',
      emoji: '🇯🇵',
      price: '55K',
      priceLabel: 'VA miles',
      detail: 'Worth $12,400 cash · 2 seats found\nTransfer Amex MR → Virgin Atlantic',
      bookUrl: '#',
      ctaText: 'See How to Book',
      isTealCta: true,
    },
    {
      id: 'p2',
      type: 'bonus' as const,
      badge: '⚡ Bonus Live',
      route: '40% Amex → Virgin Atlantic',
      emoji: '💳',
      price: 'Ends April 30',
      detail: 'ANA First Class: 55K → 40K Amex pts\nSaves $225 per ticket · 6 days left',
      bookUrl: '#',
      ctaText: 'Use This Bonus',
    },
    {
      id: 'p3',
      type: 'hotel' as const,
      badge: '🏨 Points Hotel',
      route: 'Park Hyatt Tokyo',
      emoji: '🏯',
      price: '25K',
      priceLabel: 'pts/night',
      detail: 'Worth $450/night · Chase → Hyatt\n50K Chase UR = 2 free nights',
      bookUrl: 'https://www.booking.com/?aid=7914697',
      ctaText: 'Book with Points',
      isTealCta: true,
    },
    {
      id: 'p4',
      type: 'complete_trip' as const,
      badge: '🌍 Complete Trip',
      route: 'Bali · Full Trip',
      emoji: '🏖️',
      price: '$47',
      priceLabel: 'total',
      detail: 'ANA Business + 5 nights Hyatt\n35K Amex + 40K Chase · Worth $5,500',
      bookUrl: '#',
      ctaText: 'See Full Breakdown',
      isTealCta: true,
    },
  ],
  flights: [
    {
      id: 'f1',
      type: 'flight' as const,
      badge: '✈️ Flight',
      route: 'JFK → London',
      emoji: '🇬🇧',
      price: '$312',
      savings: '54% off',
      detail: 'British Airways · RT · May 3–22',
      bookUrl: 'https://www.aviasales.com/?marker=716647&origin=JFK&destination=LHR&depart_date=2026-05-03&return_date=2026-05-22',
      ctaText: 'Book on Aviasales',
    },
    {
      id: 'f2',
      type: 'flight' as const,
      badge: '✈️ Flight',
      route: 'LAX → Bali',
      emoji: '🇮🇩',
      price: '$487',
      savings: '56% off',
      detail: 'ANA via Tokyo · RT · Oct 12–22',
      bookUrl: 'https://www.aviasales.com/?marker=716647&origin=LAX&destination=DPS&depart_date=2026-10-12&return_date=2026-10-22',
      ctaText: 'Book on Aviasales',
    },
    {
      id: 'f3',
      type: 'flight' as const,
      badge: '✈️ Flight',
      route: 'SFO → Tokyo',
      emoji: '🇯🇵',
      price: '$647',
      savings: '41% off',
      detail: 'ANA Nonstop · RT · Oct 2026',
      bookUrl: 'https://www.aviasales.com/?marker=716647&origin=SFO&destination=NRT&depart_date=2026-10-01&return_date=2026-10-14',
      ctaText: 'Book on Aviasales',
    },
    {
      id: 'f4',
      type: 'flight' as const,
      badge: '✈️ Flight',
      route: 'JFK → Cancún',
      emoji: '🇲🇽',
      price: '$198',
      savings: '62% off',
      detail: 'JetBlue Nonstop · RT · May 1–15',
      bookUrl: 'https://www.aviasales.com/?marker=716647&origin=JFK&destination=CUN&depart_date=2026-05-01&return_date=2026-05-15',
      ctaText: 'Book on Aviasales',
    },
  ],
};

export const FEATURED_DEAL = {
  badge: '🚨 Live Error Fare',
  route: 'JFK → MILAN, ITALY',
  price: '$143',
  wasPrice: '$850',
  savings: '83% OFF',
  detail: 'TAP Air Portugal via Lisbon · Roundtrip\nMay 5–15 · May 12–22 · May 19–29 · Airlines must refund if they cancel within 24 hrs',
  bookUrl: 'https://www.aviasales.com/?marker=716647&origin=JFK&destination=MXP&depart_date=2026-05-05&return_date=2026-05-15',
  foundMinutesAgo: 23,
};

export const ARIA_DEFAULT = {
  headline: 'Aria says · your AI travel guide · online now',
  message: 'Hey! I just found this Milan deal 23 minutes ago. Good news — you can do this trip completely free with Chase points. Transfer 28K UR → Turkish Miles. That\'s a $25 total cost. The Chase Sapphire bonus covers 2 people with miles left over.',
  ctaText: 'Aria, show me how →',
  ctaUrl: '#aria',
  steps: [
    'Apply for **Chase Sapphire Preferred** ($95/yr, 60K bonus points)',
    'Transfer **28K Chase UR → Turkish Miles** (1:1, instant, free)',
    'Book **JFK → MXP on Turkish.com** for ~$25 in taxes',
  ],
};

export const THEME = {
  teal: '#00C9A7',
  coral: '#FF6B6B',
  navy: '#0f0d2e',
  cream: '#f9f7f4',
  lightText: 'rgba(15,13,46,0.6)',
  mutedText: 'rgba(15,13,46,0.5)',
  subtleText: 'rgba(15,13,46,0.07)',
  fonts: {
    anton: "'Anton', sans-serif",
    condiment: "'Condiment', cursive",
    inter: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
};
