// Airport code → human-readable city name
export const AIRPORT_CITIES: Record<string, string> = {
  SJC: 'San Jose',
  SFO: 'San Francisco',
  OAK: 'Oakland',
  JFK: 'New York',
  EWR: 'Newark',
  LGA: 'New York',
  LAX: 'Los Angeles',
  BUR: 'Burbank',
  SNA: 'Orange County',
  ORD: 'Chicago',
  MDW: 'Chicago',
  MIA: 'Miami',
  FLL: 'Fort Lauderdale',
  ATL: 'Atlanta',
  DFW: 'Dallas',
  DAL: 'Dallas',
  SEA: 'Seattle',
  BOS: 'Boston',
  DEN: 'Denver',
  HNL: 'Honolulu',
  OGG: 'Maui',
  LAS: 'Las Vegas',
  DTW: 'Detroit',
  PHX: 'Phoenix',
  SLC: 'Salt Lake City',
  IAH: 'Houston',
  HOU: 'Houston',
  CLT: 'Charlotte',
  RDU: 'Raleigh',
  SMF: 'Sacramento',
  SCK: 'Stockton',
  PDX: 'Portland',
  MSP: 'Minneapolis',
  STL: 'St. Louis',
  MKE: 'Milwaukee',
  PIT: 'Pittsburgh',
  CLE: 'Cleveland',
  IND: 'Indianapolis',
  CMH: 'Columbus',
  BNA: 'Nashville',
  AUS: 'Austin',
  SAT: 'San Antonio',
  JAX: 'Jacksonville',
  MEM: 'Memphis',
  ABQ: 'Albuquerque',
  TUS: 'Tucson',
  OKC: 'Oklahoma City',
  RIC: 'Richmond',
  BWI: 'Baltimore',
  DCA: 'Washington DC',
  IAD: 'Washington DC',
  MCO: 'Orlando',
  TPA: 'Tampa',
  SAN: 'San Diego',
  // International
  NRT: 'Tokyo',
  HND: 'Tokyo',
  CDG: 'Paris',
  LHR: 'London',
  FCO: 'Rome',
  BCN: 'Barcelona',
  MAD: 'Madrid',
  AMS: 'Amsterdam',
  FRA: 'Frankfurt',
  ZRH: 'Zurich',
  VIE: 'Vienna',
  LIS: 'Lisbon',
  ATH: 'Athens',
  DPS: 'Bali',
  CUN: 'Cancún',
  MLE: 'Maldives',
  ICN: 'Seoul',
  BKK: 'Bangkok',
  SIN: 'Singapore',
  DXB: 'Dubai',
  HKG: 'Hong Kong',
  SYD: 'Sydney',
  MEL: 'Melbourne',
  GRU: 'São Paulo',
  EZE: 'Buenos Aires',
  YYZ: 'Toronto',
  YVR: 'Vancouver',
  DEL: 'Delhi',
  BOM: 'Mumbai',
  MXP: 'Milan',
  MIL: 'Milan',
  CAI: 'Cairo',
  CPT: 'Cape Town',
  JNB: 'Johannesburg',
  MEX: 'Mexico City',
  BOG: 'Bogotá',
  LIM: 'Lima',
  SCL: 'Santiago',
};

export function getAirportCity(code: string): string {
  return AIRPORT_CITIES[code] || code;
}

// US domestic airports set
export const US_AIRPORTS = new Set([
  'SJC','SFO','OAK','JFK','EWR','LGA','LAX','BUR','SNA','ORD','MDW',
  'MIA','FLL','ATL','DFW','DAL','SEA','BOS','DEN','HNL','OGG','LAS',
  'DTW','PHX','SLC','IAH','HOU','CLT','RDU','SMF','SCK','PDX','MSP',
  'STL','MKE','PIT','CLE','IND','CMH','BNA','AUS','SAT','JAX','MEM',
  'ABQ','TUS','OKC','RIC','BWI','DCA','IAD','MCO','TPA','SAN',
]);

export function isDomestic(destinationAirport: string): boolean {
  return US_AIRPORTS.has(destinationAirport?.toUpperCase());
}
