// Airport code → human-readable city name
// ~220 airports — US domestic + major international
export const AIRPORT_CITIES: Record<string, string> = {
  // ── US: Northeast ─────────────────────────────────────────────────
  JFK: 'New York',
  LGA: 'New York',
  EWR: 'Newark',
  BOS: 'Boston',
  PHL: 'Philadelphia',
  BWI: 'Baltimore',
  DCA: 'Washington DC',
  IAD: 'Washington DC',
  RIC: 'Richmond',
  RDU: 'Raleigh',
  CLT: 'Charlotte',
  PIT: 'Pittsburgh',
  CLE: 'Cleveland',
  BUF: 'Buffalo',
  SYR: 'Syracuse',
  ALB: 'Albany',
  PVD: 'Providence',
  BDL: 'Hartford',
  MHT: 'Manchester NH',
  BTV: 'Burlington',
  PWM: 'Portland ME',
  ORF: 'Norfolk',
  GSO: 'Greensboro',
  CHS: 'Charleston SC',
  SAV: 'Savannah',

  // ── US: Southeast ─────────────────────────────────────────────────
  ATL: 'Atlanta',
  MIA: 'Miami',
  FLL: 'Fort Lauderdale',
  MCO: 'Orlando',
  TPA: 'Tampa',
  JAX: 'Jacksonville',
  PBI: 'West Palm Beach',
  SRQ: 'Sarasota',
  RSW: 'Fort Myers',
  BNA: 'Nashville',
  MEM: 'Memphis',
  BHM: 'Birmingham',
  HSV: 'Huntsville',
  JAN: 'Jackson MS',
  MSY: 'New Orleans',
  MOB: 'Mobile',
  TLH: 'Tallahassee',

  // ── US: Midwest ───────────────────────────────────────────────────
  ORD: 'Chicago',
  MDW: 'Chicago',
  DTW: 'Detroit',
  MSP: 'Minneapolis',
  STL: 'St. Louis',
  MKE: 'Milwaukee',
  IND: 'Indianapolis',
  CMH: 'Columbus',
  CVG: 'Cincinnati',
  DAY: 'Dayton',
  GRR: 'Grand Rapids',
  MCI: 'Kansas City',
  ICT: 'Wichita',
  OMA: 'Omaha',
  DSM: 'Des Moines',
  MSN: 'Madison',
  CID: 'Cedar Rapids',
  FSD: 'Sioux Falls',
  FAR: 'Fargo',
  RAP: 'Rapid City',

  // ── US: South/Central ─────────────────────────────────────────────
  DFW: 'Dallas',
  DAL: 'Dallas',
  IAH: 'Houston',
  HOU: 'Houston',
  AUS: 'Austin',
  SAT: 'San Antonio',
  ELP: 'El Paso',
  ABQ: 'Albuquerque',
  TUS: 'Tucson',
  OKC: 'Oklahoma City',
  TUL: 'Tulsa',
  LIT: 'Little Rock',
  XNA: 'Bentonville',

  // ── US: Mountain/West ─────────────────────────────────────────────
  DEN: 'Denver',
  SLC: 'Salt Lake City',
  PHX: 'Phoenix',
  LAS: 'Las Vegas',
  RNO: 'Reno',
  BOI: 'Boise',
  BZN: 'Bozeman',
  MSO: 'Missoula',
  GEG: 'Spokane',
  PDX: 'Portland',
  SEA: 'Seattle',
  FAT: 'Fresno',
  SMF: 'Sacramento',
  SCK: 'Stockton',
  SBA: 'Santa Barbara',

  // ── US: California ────────────────────────────────────────────────
  LAX: 'Los Angeles',
  SFO: 'San Francisco',
  SJC: 'San Jose',
  OAK: 'Oakland',
  BUR: 'Burbank',
  SNA: 'Orange County',
  SAN: 'San Diego',
  LGB: 'Long Beach',
  ONT: 'Ontario CA',
  PSP: 'Palm Springs',

  // ── US: Hawaii / Alaska ───────────────────────────────────────────
  HNL: 'Honolulu',
  OGG: 'Maui',
  KOA: 'Kona',
  LIH: 'Kauai',
  ITO: 'Hilo',
  ANC: 'Anchorage',
  FAI: 'Fairbanks',
  JNU: 'Juneau',

  // ── Caribbean ─────────────────────────────────────────────────────
  SJU: 'San Juan',
  STT: 'St. Thomas',
  NAS: 'Nassau',
  GCM: 'Grand Cayman',
  MBJ: 'Montego Bay',
  KIN: 'Kingston',
  PUJ: 'Punta Cana',
  SDQ: 'Santo Domingo',
  HAV: 'Havana',
  BGI: 'Barbados',
  ANU: 'Antigua',
  SXM: 'St. Maarten',
  UVF: 'St. Lucia',
  POS: 'Port of Spain',

  // ── Mexico / Central America ───────────────────────────────────────
  CUN: 'Cancún',
  MEX: 'Mexico City',
  GDL: 'Guadalajara',
  MTY: 'Monterrey',
  SJD: 'Los Cabos',
  MZT: 'Mazatlán',
  PVR: 'Puerto Vallarta',
  OAX: 'Oaxaca',
  MID: 'Mérida',
  CZM: 'Cozumel',
  GUA: 'Guatemala City',
  SAL: 'San Salvador',
  SJO: 'San José CR',
  PTY: 'Panama City',

  // ── South America ─────────────────────────────────────────────────
  GRU: 'São Paulo',
  GIG: 'Rio de Janeiro',
  BSB: 'Brasília',
  FOR: 'Fortaleza',
  REC: 'Recife',
  EZE: 'Buenos Aires',
  SCL: 'Santiago',
  LIM: 'Lima',
  BOG: 'Bogotá',
  MDE: 'Medellín',
  CTG: 'Cartagena',
  UIO: 'Quito',
  GYE: 'Guayaquil',
  MVD: 'Montevideo',
  CCS: 'Caracas',

  // ── Europe: UK & Ireland ──────────────────────────────────────────
  LHR: 'London',
  LGW: 'London',
  STN: 'London',
  LTN: 'London',
  DUB: 'Dublin',
  MAN: 'Manchester',
  BHX: 'Birmingham',
  EDI: 'Edinburgh',
  GLA: 'Glasgow',
  BRS: 'Bristol',

  // ── Europe: Western ───────────────────────────────────────────────
  CDG: 'Paris',
  ORY: 'Paris',
  AMS: 'Amsterdam',
  FRA: 'Frankfurt',
  MUC: 'Munich',
  DUS: 'Düsseldorf',
  HAM: 'Hamburg',
  BER: 'Berlin',
  ZRH: 'Zurich',
  GVA: 'Geneva',
  VIE: 'Vienna',
  FCO: 'Rome',
  CIA: 'Rome',
  MXP: 'Milan',
  MIL: 'Milan',
  VCE: 'Venice',
  NAP: 'Naples',
  BCN: 'Barcelona',
  MAD: 'Madrid',
  AGP: 'Málaga',
  PMI: 'Palma',
  LIS: 'Lisbon',
  OPO: 'Porto',
  FAO: 'Faro',
  BRU: 'Brussels',
  CPH: 'Copenhagen',
  ARN: 'Stockholm',
  OSL: 'Oslo',
  HEL: 'Helsinki',
  KEF: 'Reykjavík',

  // ── Europe: Eastern & Mediterranean ──────────────────────────────
  ATH: 'Athens',
  SKG: 'Thessaloniki',
  HER: 'Heraklion',
  JTR: 'Santorini',
  CFU: 'Corfu',
  RHO: 'Rhodes',
  PRG: 'Prague',
  BUD: 'Budapest',
  WAW: 'Warsaw',
  KRK: 'Kraków',
  BEG: 'Belgrade',
  ZAG: 'Zagreb',
  SOF: 'Sofia',
  OTP: 'Bucharest',
  RIX: 'Riga',
  TLL: 'Tallinn',
  VNO: 'Vilnius',

  // ── Middle East ───────────────────────────────────────────────────
  DXB: 'Dubai',
  AUH: 'Abu Dhabi',
  DOH: 'Doha',
  KWI: 'Kuwait City',
  BAH: 'Bahrain',
  MCT: 'Muscat',
  AMM: 'Amman',
  BEY: 'Beirut',
  TLV: 'Tel Aviv',
  CAI: 'Cairo',
  SSH: 'Sharm el-Sheikh',
  HRG: 'Hurghada',
  IST: 'Istanbul',
  SAW: 'Istanbul',
  AYT: 'Antalya',
  JED: 'Jeddah',
  RUH: 'Riyadh',

  // ── Africa ────────────────────────────────────────────────────────
  CPT: 'Cape Town',
  JNB: 'Johannesburg',
  NBO: 'Nairobi',
  ADD: 'Addis Ababa',
  ZNZ: 'Zanzibar',
  CMN: 'Casablanca',
  RAK: 'Marrakech',
  ACC: 'Accra',
  LOS: 'Lagos',
  DKR: 'Dakar',
  MRU: 'Mauritius',
  SEZ: 'Seychelles',

  // ── South / Southeast Asia ────────────────────────────────────────
  DEL: 'Delhi',
  BOM: 'Mumbai',
  BLR: 'Bangalore',
  MAA: 'Chennai',
  CCU: 'Kolkata',
  HYD: 'Hyderabad',
  COK: 'Kochi',
  GOI: 'Goa',
  KTM: 'Kathmandu',
  CMB: 'Colombo',
  MLE: 'Maldives',
  BKK: 'Bangkok',
  DMK: 'Bangkok',
  CNX: 'Chiang Mai',
  HKT: 'Phuket',
  USM: 'Koh Samui',
  SIN: 'Singapore',
  KUL: 'Kuala Lumpur',
  PEN: 'Penang',
  DPS: 'Bali',
  CGK: 'Jakarta',
  MNL: 'Manila',
  CEB: 'Cebu',
  SGN: 'Ho Chi Minh City',
  HAN: 'Hanoi',
  DAD: 'Da Nang',
  PNH: 'Phnom Penh',
  REP: 'Siem Reap',
  RGN: 'Yangon',

  // ── East Asia ─────────────────────────────────────────────────────
  NRT: 'Tokyo',
  HND: 'Tokyo',
  KIX: 'Osaka',
  ITM: 'Osaka',
  CTS: 'Sapporo',
  OKA: 'Okinawa',
  FUK: 'Fukuoka',
  ICN: 'Seoul',
  GMP: 'Seoul',
  PUS: 'Busan',
  PEK: 'Beijing',
  PKX: 'Beijing',
  PVG: 'Shanghai',
  SHA: 'Shanghai',
  CAN: 'Guangzhou',
  SZX: 'Shenzhen',
  CTU: 'Chengdu',
  CKG: 'Chongqing',
  HGH: 'Hangzhou',
  HKG: 'Hong Kong',
  MFM: 'Macau',
  TPE: 'Taipei',
  KHH: 'Kaohsiung',

  // ── Australia / Pacific ───────────────────────────────────────────
  SYD: 'Sydney',
  MEL: 'Melbourne',
  BNE: 'Brisbane',
  PER: 'Perth',
  ADL: 'Adelaide',
  CNS: 'Cairns',
  OOL: 'Gold Coast',
  AKL: 'Auckland',
  WLG: 'Wellington',
  CHC: 'Christchurch',
  ZQN: 'Queenstown',
  NAN: 'Fiji',
  PPT: 'Tahiti',
  GUM: 'Guam',

  // ── Canada ────────────────────────────────────────────────────────
  YYZ: 'Toronto',
  YVR: 'Vancouver',
  YUL: 'Montreal',
  YYC: 'Calgary',
  YEG: 'Edmonton',
  YOW: 'Ottawa',
  YHZ: 'Halifax',
  YWG: 'Winnipeg',
};

export function getAirportCity(code: string): string {
  return AIRPORT_CITIES[code?.toUpperCase()] || code;
}

// US domestic airports set
export const US_AIRPORTS = new Set([
  // Northeast
  'JFK','LGA','EWR','BOS','PHL','BWI','DCA','IAD','RIC','RDU','CLT','PIT','CLE',
  'BUF','SYR','ALB','PVD','BDL','MHT','BTV','PWM','ORF','GSO','CHS','SAV',
  // Southeast
  'ATL','MIA','FLL','MCO','TPA','JAX','PBI','SRQ','RSW','BNA','MEM','BHM','HSV',
  'JAN','MSY','MOB','TLH',
  // Midwest
  'ORD','MDW','DTW','MSP','STL','MKE','IND','CMH','CVG','DAY','GRR',
  'MCI','ICT','OMA','DSM','MSN','CID','FSD','FAR','RAP',
  // South/Central
  'DFW','DAL','IAH','HOU','AUS','SAT','ELP','ABQ','TUS','OKC','TUL','LIT','XNA',
  // Mountain/West
  'DEN','SLC','PHX','LAS','RNO','BOI','BZN','MSO','GEG','PDX','SEA',
  'FAT','SMF','SCK','SBA',
  // California
  'LAX','SFO','SJC','OAK','BUR','SNA','SAN','LGB','ONT','PSP',
  // Hawaii/Alaska
  'HNL','OGG','KOA','LIH','ITO','ANC','FAI','JNU',
]);

export function isDomestic(destinationAirport: string): boolean {
  return US_AIRPORTS.has(destinationAirport?.toUpperCase());
}
