// Forest Sage design tokens
export const T = {
  primary: '#2D6A4F',
  primaryLight: '#E8F5EE',
  primaryDark: '#1B4332',
  accent: '#40916C',
  bg: '#FAFAF5',
  bgWarm: '#F0EDE5',
  card: '#ffffff',
  border: '#E8E5DB',
  borderHover: '#D4D0C4',
  text: '#1a1a1a',
  textSec: '#666',
  textMuted: '#999',
  error: '#C0432A',
  errorBg: '#FDEAE6',
  hotel: '#5B4B8A',
  hotelBg: '#EDE8F5',
  pointsBg: '#FFF8E1',
  pointsText: '#8B6914',
  radius: '12px',
  radiusSmall: '8px',
  font: "'DM Sans', sans-serif",
  fontSerif: "'Fraunces', serif",
  fontMono: "'JetBrains Mono', monospace",
} as const;
